package com.magmaguy.resourcepackmanager.bedrock.model;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * Generates and writes a Bedrock resource pack manifest.json.
 */
public class BedrockManifest {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    /**
     * Writes a manifest.json to the given output directory.
     *
     * @param outputDir      the directory to write manifest.json into
     * @param pluginVersion  the version string of the plugin (used for deterministic UUID seeding and metadata)
     * @param cacheBustToken any per-build-unique string (currently the build's
     *                       {@code System.currentTimeMillis()} — NOT a hash of pack
     *                       contents). Used to derive the {@code header.version} /
     *                       {@code modules[0].version} triplet so each build emits a
     *                       different version, forcing Bedrock to invalidate its
     *                       (uuid, version)-keyed pack cache. If callers ever want
     *                       reproducible builds (identical pack contents → identical
     *                       manifest), pass a content-derived digest here instead.
     */
    public static void write(File outputDir, String pluginVersion, String cacheBustToken) {
        if (outputDir == null) return;
        if (!outputDir.exists()) outputDir.mkdirs();

        // MA2: content-stable UUIDs derived from the plugin version, not from
        // System.currentTimeMillis(). Pack identity stays consistent across rebuilds of
        // the same plugin version so Bedrock recognises it as "the same pack".
        String safeVersion = pluginVersion != null && !pluginVersion.isEmpty() ? pluginVersion : "unknown";
        UUID headerUuid = UUID.nameUUIDFromBytes(("rspm_bedrock_header:" + safeVersion).getBytes(StandardCharsets.UTF_8));
        UUID moduleUuid = UUID.nameUUIDFromBytes(("rspm_bedrock_module:" + safeVersion).getBytes(StandardCharsets.UTF_8));

        // Bump the version triplet per build from the cache-bust token so Bedrock's cache
        // invalidates each run. Bedrock matches packs by (uuid, version) — keeping
        // version pinned at [1,0,0] means clients keep serving the cached old bytes
        // forever. The token today is a timestamp, so this fires on every build even
        // when contents are unchanged; that's intentional for a dev/server workflow
        // where pack contents nearly always differ between builds.
        int[] versionTriplet = deriveVersionTriplet(cacheBustToken);

        Map<String, Object> manifest = new LinkedHashMap<>();
        manifest.put("format_version", 2);

        Map<String, Object> header = new LinkedHashMap<>();
        header.put("name", "ResourcePackManager Bedrock Pack");
        header.put("description", "Auto-generated Bedrock resource pack");
        header.put("uuid", headerUuid.toString());
        header.put("version", Arrays.asList(versionTriplet[0], versionTriplet[1], versionTriplet[2]));
        header.put("min_engine_version", Arrays.asList(1, 21, 0));
        manifest.put("header", header);

        // MA1: Rainbow always writes modules[0].name and modules[0].description.
        Map<String, Object> module = new LinkedHashMap<>();
        module.put("type", "resources");
        module.put("name", "ResourcePackManager Resources");
        module.put("description", "Generated by ResourcePackManager");
        module.put("uuid", moduleUuid.toString());
        module.put("version", Arrays.asList(versionTriplet[0], versionTriplet[1], versionTriplet[2]));
        manifest.put("modules", Collections.singletonList(module));

        Map<String, Object> metadata = new LinkedHashMap<>();
        metadata.put("authors", Collections.singletonList("ResourcePackManager"));
        Map<String, Object> generatedWith = new LinkedHashMap<>();
        generatedWith.put("ResourcePackManager", Collections.singletonList(safeVersion));
        metadata.put("generated_with", generatedWith);
        manifest.put("metadata", metadata);

        File manifestFile = new File(outputDir, "manifest.json");
        try (FileWriter writer = new FileWriter(manifestFile, StandardCharsets.UTF_8)) {
            GSON.toJson(manifest, writer);
        } catch (IOException e) {
            com.magmaguy.magmacore.util.Logger.warn("Failed to write Bedrock manifest.json: " + e.getMessage());
        }
    }

    /**
     * Derive a 3-element {@code [major, minor, patch]} version triplet from the
     * cache-bust token so each build emits a different version (forcing Bedrock client
     * cache invalidation), while still fitting within Bedrock's semver-style version
     * field. Each component is bounded to 0..999 to stay readable in tooling.
     */
    private static int[] deriveVersionTriplet(String cacheBustToken) {
        long seed;
        if (cacheBustToken == null || cacheBustToken.isEmpty()) {
            seed = System.currentTimeMillis();
        } else {
            try {
                seed = Long.parseLong(cacheBustToken);
            } catch (NumberFormatException nfe) {
                seed = cacheBustToken.hashCode() & 0xffffffffL;
            }
        }
        long abs = seed < 0 ? -seed : seed;
        int patch = (int) (abs % 1000);
        int minor = (int) ((abs / 1000) % 1000);
        int major = (int) ((abs / 1_000_000) % 1000);
        // Major must be >= 1 — Bedrock rejects version arrays starting with 0 in some
        // contexts and we want at least one non-zero component so the pack looks valid.
        if (major == 0) major = 1;
        return new int[]{major, minor, patch};
    }
}
