name: ResourcePackManager
main: com.magmaguy.resourcepackmanager.ResourcePackManager
version: 1.3.0
api-version: 1.14
author: MagmaGuy
softdepend:
- EliteMobs
- FreeMinecraftModels
- ModelEngine
- Nova
- Oraxen
- ItemsAdder
- BackpackPlus
- vane-core
- RealisticSurvival

commands:
  resourcepackmanager:
    aliases:
      - rspm
    description: "Main command"
  logify:
    description: Posts current latest.log in mclo.gs, to make reporting bugs easier for admins.
permissions:
  logify.*:
    description: Lets admins run the /logify command, which sends the current latest server log to mclo.gs.
    default: op