name: ResourcePackManager
main: com.magmaguy.resourcepackmanager.ResourcePackManager
version: 1.7.5
api-version: 1.14
author: MagmaGuy
softdepend:
  - EliteMobs
  - FreeMinecraftModels
  - ModelEngine
  - Nova
  - Oraxen
  - ItemsAdder
  - BackpackPlus
  - BetterHUD
  - InfiniteVehicles
  - MegaBlockSurvivors
  - MMOInventory
  - Nexo
  - ValhallaMMO
  - vane-core
  - RealisticSurvival

commands:
  resourcepackmanager:
    aliases:
      - rspm
    description: "Main command"
