package com.magmaguy.resourcepackmanager.mixer;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

class MixFingerprintTest {
    @TempDir
    Path temporaryDirectory;

    @Test
    void changedMixerOutputRevisionInvalidatesUnchangedInputs() throws Exception {
        Path input = temporaryDirectory.resolve("source-pack.zip");
        Files.write(input, new byte[]{1, 2, 3, 4});

        String previousBuild = Mix.calculateInputFingerprint(
                List.of(input.toFile()), "entity-atlas-v1", () -> false);
        String sameBuild = Mix.calculateInputFingerprint(
                List.of(input.toFile()), "entity-atlas-v1", () -> false);
        String replacementBuild = Mix.calculateInputFingerprint(
                List.of(input.toFile()), "blocks-atlas-v2", () -> false);

        assertEquals(previousBuild, sameBuild);
        assertNotEquals(previousBuild, replacementBuild,
                "A code-only mixer replacement must not reuse output generated by older semantics");
    }
}
